name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Restore dependencies
      run: dotnet restore TestApp\TestApp.csproj
      
    - name: Build
      run: dotnet build -c Release TestApp\TestApp.csproj

    - name: Upload TestApp zip
      uses: actions/upload-artifact@v4
      with:
        name: TestApp
        path: .\TestApp\TestApp.csproj
        if-no-files-found: ignore
        retention-days: 5
      
    - name: Test
      run: ./TestApp/bin/Release/net8.0/TestApp ${{ github.repository_owner }} ${{ github.event.repository.name }} ${{ secrets.GITHUB_TOKEN }}
